spring.application.name=techcom
spring.datasource.url=jdbc:mysql://localhost:3306/eduhub
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
#spring.datasource.password=password // optional if local host 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=5001


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.main.allow-bean-definition-overriding=true

#multimedia
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
